### ISSUE TITLE
Feature Request: mcc-mnc translation

### ISSUE THREAD

**Issue by anoo2niem** [sharyer/gsmevil2#20]
Hi, 

Thanks for this nice web interface!
I would like to propose a feature, to implement some sort of translation to the actual country & network.

This could be used for the data: https://mcc-mnc.com/
simple-imsi-catcher has this feature aswell, maybe it would be 'easier' to port it over from there.
If i knew how to code i would happily contribute, but unfortunatly i'm not a coder...

Thanks again!

**Comment by ninjhacks** [comment]
yeah we can add but first, this project is discontinued I have an idea for a new version I will develop when I get free time 2nd country is not helpful because the country will be the country where you run this and the network will be same on which you which frequency you run unless you running on very wide range of frequency which cover multiple networks.

**Comment by anoo2niem** [comment]
The country thing could be true in your region, but in my case for example when i run simple-imsi-catcher cli interface on a specific band (i.e. 925.8M), i see a lot of different countries appear. I live in a city with many different nationalities, who either visit, work here, etc.

**Comment by ninjhacks** [comment]
I got your point but this project is discontinued I will add it in the next version if i make.
